Challenge 1 ✅ — Highest Paid Per Department

SELECT FIRST_NAME, DEPARTMENT_ID, SALARY FROM (
  SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY,
  ROW_NUMBER() OVER (PARTITION BY DEPARTMENT_ID 
  ORDER BY SALARY DESC) AS RN 
  FROM hr.EMPLOYEES)
WHERE RN = 1;


### Challenge 2 ✅ — Employee Salary vs Department Average

SELECT SALARY, DEPARTMENT_ID, 
AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID) 
FROM HR.EMPLOYEES;


### Challenge 3 ✅ — ROW_NUMBER, RANK, DENSE_RANK Together

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY,
RANK() OVER (ORDER BY SALARY DESC) AS RNK,
DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DENSE_RNK,
ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS ROW_NUM
FROM HR.EMPLOYEES E;


### Challenge 4 ✅ — Previous Employee Salary Using LAG


SELECT EMPLOYEE_ID, HIRE_DATE, SALARY,
LAG(SALARY) OVER (ORDER BY HIRE_DATE DESC),
SALARY - LAG(SALARY) OVER (ORDER BY HIRE_DATE DESC) AS SALARY_DIFF
FROM HR.EMPLOYEES;


### Challenge 5 ✅ — Running Total Per Department
SELECT EMPLOYEE_ID, SALARY,
SUM(SALARY) OVER (PARTITION BY DEPARTMENT_ID 
ORDER BY HIRE_DATE) 
FROM HR.EMPLOYEES;
